kind: pipeline
name: default-1

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn install

kind: pipeline
type: docker
name: default

steps:
- name: build
  image: fabrica-drone-1
  commands:
  - go build
  - go test

trigger:
  branch:
  - master
  - Dev/*
  - Uat/*
  - Prod/*
